### ISSUE TITLE
Bug: the create insight page is not stable

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1505]
### Describe the bug

if we go to create insight page and add multiple repositories the repositories cart will be too long and will need to scroll down the page to be able to see the create button. 

I think this desgin could have another UI/UX experience. 

https://github.com/open-sauced/insights/assets/18273833/57663210-0483-4f0e-b852-90aac9b50a75

### Steps to reproduce

1. https://insights.opensauced.pizza/hub/insights/new
2. add multilpe repos around 15
3. you can see that the create button is moving down. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
setting the height of the repo list container to 90vh and adding an overflow-y-auto should fix this

**Comment by a0m0rajab** [comment]
@dev-phantom thanks for the suggestions! if you like feel free to grab it.

**Comment by dev-phantom** [comment]
.take

**Comment by a0m0rajab** [comment]
It's still reproduceable: 

https://github.com/open-sauced/app/assets/18273833/ce047e86-1436-4875-b034-77f8c8538bc5

**Comment by dev-phantom** [comment]
for some reason i'm unable to reproduce it here 
![image](https://github.com/open-sauced/app/assets/72051159/df24c2e3-9f40-4b29-9ab5-23c6d9bd7483)

can you try the latest release?

**Comment by a0m0rajab** [comment]
you added 4 repos in the basket/cart, you need to add more to test it.

**Comment by dev-phantom** [comment]
opps just got what you meant 
I'm working on this now 

Thanks for taking your time to point this out

**Comment by a0m0rajab** [comment]
You are welcome! Thank you for your time to work on it!

**Comment by dev-phantom** [comment]
> You are welcome! Thank you for your time to work on it!

please i am having this issue anytime i am on github codespace and in try to signIn locally i get redirected to https://beta.insights.opensauced.pizza/hub/insights and any change i make locally wont be affected in the https://beta.insights.opensauced.pizza/hub/insights
how do i resolve this?

https://github.com/open-sauced/app/assets/72051159/1d68e945-e107-4e55-ac42-ecbe7e67fc5f

**Comment by ThePiyushAggarwal** [comment]
I haven't used GitHub Codespaces for this. But maybe try pasting the code you see in URL to your GitHub Codespaces URL?

**Comment by dev-phantom** [comment]
> I haven't used GitHub Codespaces for this. But maybe try pasting the code you see in URL to your GitHub Codespaces URL?

I just got a mail that I've used 100% of my codespace for this month
But you can try creating a codespace on your end you will be able to reproduce it

**Comment by ThePiyushAggarwal** [comment]
If you were able to record it, it must be reproducible.

**Comment by dev-phantom** [comment]
> If you were able to record it, it must be reproducible.

Yes I know
What I'm trying to say is create a new codespace on your end I can't share the link to this codespace cause ive exhausted my quota for this month
![Screenshot_20230826-192725](https://github.com/open-sauced/app/assets/72051159/a08f0607-61ea-449d-bab3-a61ac62c014c)

**Comment by ThePiyushAggarwal** [comment]
Why do you need to share the link to your codespaces?

**Comment by ThePiyushAggarwal** [comment]
Messaged you on discord to avoid sending everyone notifications.

**Comment by a0m0rajab** [comment]
@dev-phantom the codespace issue is out of scope for this one, could you open an issue for that and have the discussion there? 
@ThePiyushAggarwal it would be great to have to the discussion on public to let other developers be aware of the situation and development.

**Comment by dev-phantom** [comment]
> @dev-phantom the codespace issue is out of scope for this one, could you open an issue for that and have the discussion there? @ThePiyushAggarwal it would be great to have to the discussion on public to let other developers be aware of the situation and development.

Okay I'll open an issue in bit

**Comment by dev-phantom** [comment]
Hi there,
I appreciate the opportunity to contribute to this project. However, I regret to inform you that I won't be able to fix this issue at the moment. The project relies on Next.js, and my current processor is a dual-core, which limits my ability to effectively work with Next.js projects, especially when dealing with a large codebase.

I apologize for any inconvenience this may cause and hope that someone else with better hardware can address this issue.

**Comment by dev-phantom** [comment]
@OpherM can you work on this?
